const properties = [
  {
    id: 1,
    title: "Luxury Chelsea Apartment",
    type: "Apartment",
    status: "For Sale",
    price: 850000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    location: { city: "London", state: "Greater London", address: "14 Sloane Avenue, Chelsea, SW3" },
    description:
      "An exceptional two-bedroom apartment in the heart of Chelsea, offering beautifully proportioned living spaces with high ceilings and period features throughout. The open-plan kitchen and reception room leads to a private balcony overlooking a quiet garden square. Within walking distance of the King's Road, top restaurants, and excellent transport links.",
    features: ["Private Balcony", "Concierge", "Gym", "Roof Terrace", "Parking", "Porter"],
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    ],
    agent: { name: "Charlotte Pemberton", phone: "+44 20 7946 0100", email: "charlotte@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=47" },
    listedDate: "2024-11-15",
    isFeatured: true,
  },
  {
    id: 2,
    title: "Edwardian Family Home",
    type: "House",
    status: "For Sale",
    price: 975000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    location: { city: "Manchester", state: "Greater Manchester", address: "37 Lapwing Lane, Didsbury, M20" },
    description:
      "A substantial Edwardian semi-detached home on one of Didsbury's most sought-after roads. Beautifully extended and refurbished throughout, with a superb open-plan kitchen-diner, four generous bedrooms, and a large south-facing garden. Top-rated schools, Didsbury village, and the tram network are all moments away.",
    features: ["Large Garden", "Garage", "Loft Conversion", "Underfloor Heating", "Home Office", "Smart Home"],
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    ],
    agent: { name: "James Thornton", phone: "+44 161 496 0200", email: "james@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=12" },
    listedDate: "2024-10-22",
    isFeatured: true,
  },
  {
    id: 3,
    title: "Grand Georgian Townhouse",
    type: "Townhouse",
    status: "For Sale",
    price: 1450000,
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    location: { city: "Edinburgh", state: "Scotland", address: "8 Moray Place, New Town, EH3" },
    description:
      "A magnificent five-bedroom Georgian townhouse in Edinburgh's prestigious Moray Estate. Arranged over four floors, this exceptional home features original cornicing, shuttered sash windows, grand reception rooms, and a private walled garden. A truly rare opportunity in one of Scotland's most coveted addresses.",
    features: ["Private Garden", "Original Features", "Wine Cellar", "Study", "Drawing Room", "Stone Floors"],
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    ],
    agent: { name: "Fiona MacGregor", phone: "+44 131 496 0300", email: "fiona@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=25" },
    listedDate: "2024-09-05",
    isFeatured: true,
  },
  {
    id: 4,
    title: "Converted Warehouse Loft",
    type: "Apartment",
    status: "For Rent",
    price: 2600,
    bedrooms: 1,
    bathrooms: 1,
    area: 780,
    location: { city: "London", state: "Greater London", address: "52 Redchurch Street, Shoreditch, E2" },
    description:
      "Stunning warehouse conversion in the heart of Shoreditch. This spectacular loft apartment retains original industrial features — exposed steel beams, polished concrete floors, and oversized crittall windows — alongside a fully fitted modern kitchen and bespoke bathroom. Surrounded by the best of East London's food, art, and nightlife.",
    features: ["High Ceilings", "Exposed Brickwork", "Roof Terrace Access", "Bike Storage", "Near Elizabeth Line"],
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
    ],
    agent: { name: "Oliver Hughes", phone: "+44 20 7946 0400", email: "oliver@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=33" },
    listedDate: "2024-12-01",
    isFeatured: false,
  },
  {
    id: 5,
    title: "Clifton Village Victorian Villa",
    type: "Villa",
    status: "For Sale",
    price: 1250000,
    bedrooms: 5,
    bathrooms: 3,
    area: 3200,
    location: { city: "Bristol", state: "Avon", address: "19 The Promenade, Clifton, BS8" },
    description:
      "An imposing and beautifully maintained Victorian villa in the heart of Clifton Village. This exceptional family home offers wonderfully proportioned rooms across four floors, a large south-facing garden, and breath-taking views across the Clifton Suspension Bridge and Avon Gorge. Clifton Village, the Downs, and Whiteladies Road are all on the doorstep.",
    features: ["Garden", "Parking", "Period Fireplaces", "Cellar", "Panoramic Views", "Original Cornicing"],
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    agent: { name: "Charlotte Pemberton", phone: "+44 20 7946 0100", email: "charlotte@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=47" },
    listedDate: "2024-11-28",
    isFeatured: false,
  },
  {
    id: 6,
    title: "Riverside Penthouse",
    type: "Penthouse",
    status: "For Rent",
    price: 5500,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    location: { city: "Birmingham", state: "West Midlands", address: "Penthouse 4, The Cube, Wharfside Street, B1" },
    description:
      "A spectacular three-bedroom penthouse at The Cube — Birmingham's most iconic landmark building. Boasting panoramic views of the city skyline and the canal network, this stunning apartment features a wrap-around terrace, floor-to-ceiling glass walls, a chef's kitchen, and spa-quality bathrooms. Valet parking, concierge, and a private residents' gym are all included.",
    features: ["Wrap-Around Terrace", "Panoramic Views", "Concierge", "Valet Parking", "Gym", "Canal Views"],
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80",
    ],
    agent: { name: "James Thornton", phone: "+44 161 496 0200", email: "james@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=12" },
    listedDate: "2024-12-10",
    isFeatured: true,
  },
  {
    id: 7,
    title: "Regency Period Cottage",
    type: "House",
    status: "For Sale",
    price: 595000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1400,
    location: { city: "Bath", state: "Somerset", address: "6 Cavendish Place, BA1" },
    description:
      "A charming Regency-era stone cottage in a quiet position just minutes from Bath city centre. This elegant three-bedroom home has been thoughtfully updated to blend period character with modern comfort: hand-crafted kitchen, plantation shutters, underfloor heating, and a private courtyard garden. Walking distance to the Roman Baths, Abbey, and top-rated schools.",
    features: ["Courtyard Garden", "Period Stone Facade", "Underfloor Heating", "Fireplace", "Parking Permit"],
    images: [
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&q=80",
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80",
    ],
    agent: { name: "Fiona MacGregor", phone: "+44 131 496 0300", email: "fiona@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=25" },
    listedDate: "2024-10-15",
    isFeatured: false,
  },
  {
    id: 8,
    title: "Seafront Studio Apartment",
    type: "Apartment",
    status: "For Rent",
    price: 1350,
    bedrooms: 0,
    bathrooms: 1,
    area: 480,
    location: { city: "Brighton", state: "East Sussex", address: "Flat 9, Grand Ocean Parade, Hove, BN3" },
    description:
      "A stylish and well-appointed studio apartment directly on the Hove seafront, with uninterrupted views across the English Channel. Fully furnished to a high specification with a built-in double bed, compact kitchen, and a Juliet balcony to soak up the sea air. Moments from independent cafes, boutiques, and Brighton train station.",
    features: ["Sea Views", "Juliet Balcony", "Fully Furnished", "Bike Storage", "Near Brighton Station"],
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80",
    ],
    agent: { name: "Oliver Hughes", phone: "+44 20 7946 0400", email: "oliver@estatepro.co.uk", avatar: "https://i.pravatar.cc/150?img=33" },
    listedDate: "2024-12-05",
    isFeatured: false,
  },
];

module.exports = properties;
